services:
  database:
    image: mysql:8
    container_name: sgu-database-ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sgu-aafh-10a
    ports:
      - "3307:3306"
    restart: unless-stopped

  frontend:
    image: client:1.0-sgu-ci
    build: 
      context: ./client
      dockerfile: Dockerfile.ci
      args:
        API_HOST: localhost
        API_PORT: 8081
        API_BASE: /sgu-api
    container_name: sgu-frontend-ci
    ports:
      - "3000:80"
    depends_on:
      - database

  backend:
    image: server:1.0-sgu-ci
    build: 
      context: ./server
    environment:
      SERVER_PORT: 8080
      DB_HOST: database
      DB_PORT: 3306
      DB_NAME: sgu-aafh-10a
      DB_USER: root
      DB_PASS: root
    container_name: sgu-backend-ci
    ports:
      - "8081:8080"
    depends_on:
      - frontend